name: build

on: [push]

jobs:
  build-and-push-images:
    uses: mikojs/actions/.github/workflows/build-docker.yml@main
    with:
      name: hsuting/code-server
      push: ${{ github.ref == 'refs/heads/main' }}
