name: build

on: [push]

jobs:
  build-and-push-images:
    uses: mikojs/actions/.github/workflows/build-docker.yml@main
    strategy:
      matrix:
        name: [code-server]
    with:
      registry: hsuting
      name: ${{ matrix.name }}
      context: ./${{ matrix.name }}
      file: ./${{ matrix.name }}/Dockerfile
      push: ${{ github.ref == 'refs/heads/main' }}

  final-check:
    runs-on: ubuntu-latest
    needs: build-and-push-images
    steps:
      - uses: actions/checkout@v3
